knp_paginator:
    page_range: 5                      # Number of pages in the paginator navigation
    default_options:
        page_name: page                # Page query parameter name
        sort_field_name: sort          # Sort field query parameter name
        sort_direction_name: direction # Sort direction query parameter name
        distinct: true                 # Apply DISTINCT clause to count queries
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig' # Paginator template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'                      # Sortable link template
